apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: spot-cluster
  region: us-east-1

managedNodeGroups:

# `instanceTypes` defaults to [`m5.large`]
- name: spot-cluster #cluster node group name
  spot: true
  ssh:
    publicKeyName: sasi12.pem