---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    sonar_version: 9.6.1.59531
    sonar_user: sonar
    sonar_group: sonar
    sonar_home: /opt/sonarqube
    sonar_port: 9000
  tasks:
  - name: Install openjdk-11-jdk
    apt:
      name: openjdk-11-jdk
      state: present
  - name: Create sonar user and group
    user:
      name: sonar
      group: sonar_group
      system: yes
      shell: /usr/sbin/nologin
  - name: Download sonarqube
    get_url:
      url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.6.1.59531.zip
      dest: /tmp/sonarqube.zip
  - name: Unzip sonarqube
    unarchive:
      src: /tmp/sonarqube.zip
      dest: "/opt/sonarqube"
      remote_src: yes
      become_user: root
  - name: Change ownership of sonarqube directory
    file:
      path: "/opt/sonarqube"
      owner: sonar
      group: sonar_group
  - name: Start sonarqube service
    shell: "/opt/sonarqube/bin/linux-x86-64/sonar.sh start"
  - name: Wait for sonarqube to start
    wait_for:
      port: "9000"
  - name: Open firewall port
    firewalld:
      port: "9000/tcp"
      state: enabled
