apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "150m" #1 CPU = 1000 mill1 cpu
        memory: "128Mi"   #min
      limits:
        memory: "128Mi"   #max
        cpu: "500m"   #max
    ports:
      - containerPort: 81
