apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  namespace: roboshop
spec:
  containers:
  - image: nginx:latest
    name: nginx-v2
  - image: almalinix
    name: almalinix
    command:  ["sleep", "200"]
