apiVersion: v1
kind: Pod
metadata:
  name: nginx-v2
  namespace: roboshop
  labels:
    name: nginx
spec:
  containers:
  - name: nginx-v2
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 81
  - name: almalinix:latest
    image: almalinix
    command:  ["sleep", "200"]
